export const DEFAULT_ITEM_HEIGHT = 56
export const DEFAULT_VIEWPORT_HEIGHT = 400
export const DEFAULT_OVERSCAN = 0
export const BOTTOM_THRESHOLD_PX = 4
export const SCROLL_END_DEBOUNCE_MS = 150
export const RESIZE_OBSERVER_DEBOUNCE_MS = 16
export const SMOOTH_SCROLL_DEFAULT_FRAMES = 30
